/*

 BLOB.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char blob[] =
{
  0x3C,0x3C,0x7C,0x40,0xBC,0xD4,0xB4,0xDC,
  0xBE,0xC2,0x9F,0xE1,0xCF,0xF1,0x3E,0x3E,
  0x3E,0x3E,0x6E,0x70,0x5E,0x6A,0x5A,0x6E,
  0x3F,0x21,0x5F,0x61,0x4F,0x71,0x7C,0x7C
};

/* End of BLOB.C */
